# MkDocs Workflow for GitHub Pages

name: pages-mkdocs

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install mkdocs
      - run: mkdocs build
      - name: Deploy docs
        run: mkdocs gh-deploy
